In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
mat = np.arange(0,100).reshape(10,10)

In [4]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [5]:
mat[5:9 ,:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [6]:
mat[5: ,:]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [7]:
mat[5:,4:8]

array([[54, 55, 56, 57],
       [64, 65, 66, 67],
       [74, 75, 76, 77],
       [84, 85, 86, 87],
       [94, 95, 96, 97]])

In [8]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr [arr>=4]

array([ 4,  5,  6,  7,  8,  9, 10])

In [10]:
ar = np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
ar + ar

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
ar * ar

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [15]:
ar - ar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
ar / ar

C:\Users\Volkan\AppData\Local\Temp\ipykernel_16444\1071685828.py:1: RuntimeWarning: invalid value encountered in true_divide
  ar / ar


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [18]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
ar **6

array([     0,      1,     64,    729,   4096,  15625,  46656, 117649,
       262144, 531441], dtype=int32)

In [20]:
arr **6

array([      1,      64,     729,    4096,   15625,   46656,  117649,
        262144,  531441, 1000000], dtype=int32)

In [21]:
np.divide(8,4)

2.0

In [22]:
np.multiply(3,5)

15

In [23]:
np.subtract(9,3)

6

In [24]:
np.add(2,2)

4

In [25]:
num1 = np.arange(1,21)
num1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
num2 = np.arange(1,21)
num2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
num1 *num2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [28]:
num1 +num2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [29]:
num1 -num2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
num1 **num2

array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489,  1410065408,
        1843829075,  -251658240, -1692154371, -1282129920,  1500973039,
                 0,  1681328401,   457441280,  -306639989,           0],
      dtype=int32)

In [31]:
num1 /num2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [32]:
num1 *num1

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [33]:
num2 *num2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400])

In [34]:
num1 +num1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [35]:
num2 +num2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

In [36]:
num1 -num1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
num2 -num2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
num1 **num1

array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489,  1410065408,
        1843829075,  -251658240, -1692154371, -1282129920,  1500973039,
                 0,  1681328401,   457441280,  -306639989,           0],
      dtype=int32)

In [39]:
num2 **num2

array([          1,           4,          27,         256,        3125,
             46656,      823543,    16777216,   387420489,  1410065408,
        1843829075,  -251658240, -1692154371, -1282129920,  1500973039,
                 0,  1681328401,   457441280,  -306639989,           0],
      dtype=int32)

In [40]:
num1 /num1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [41]:
num2 /num2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])